// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtyDYYPUAZJhsl9HEiAnLA3rLwGuUNgl4',
    appId: '1:974224901790:web:6df400eee9b062eb5fdd8f',
    messagingSenderId: '974224901790',
    projectId: 'shoea-8a483',
    authDomain: 'shoea-8a483.firebaseapp.com',
    storageBucket: 'shoea-8a483.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-RbejG3K1G0QhMhzZfKcI2ajzJ1_oa4k',
    appId: '1:974224901790:android:8b25815dad9d7c525fdd8f',
    messagingSenderId: '974224901790',
    projectId: 'shoea-8a483',
    storageBucket: 'shoea-8a483.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtyDYYPUAZJhsl9HEiAnLA3rLwGuUNgl4',
    appId: '1:974224901790:web:f475a3016cec19df5fdd8f',
    messagingSenderId: '974224901790',
    projectId: 'shoea-8a483',
    authDomain: 'shoea-8a483.firebaseapp.com',
    storageBucket: 'shoea-8a483.firebasestorage.app',
  );
}
